SEED = True
BATCH_SIZE = 32
GAMMA = 0.999
EPS_START = 0.9
EPS_END = 0.05
EPS_DECAY = 1000
TARGET_UPDATE = 10
VTR_OUTPUT_DIM = 768
HIDDEN_DIM = 512
CACHE_FRONT = 'cache/screen_front.png'
CACHE_BEHIND = 'cache/screen_behind.png'
BOUND_PATTERN = '\\[-?(\\d+),-?(\\d+)\\]\\[-?(\\d+),-?(\\d+)\\]'
thresholdValue = 0.9
DEVICE_NAME = 'xiaomi'
REPLAY_RESOLUTION_X = 1080
REPLAY_RESOLUTION_Y = 2280
EPSILON = 0.7
# ROW = 40
ROW = 35
# COLUMN = 15
COLUMN = 20
IMG_SIM_TYPE = 'Euclidean' # Cosine
IMG_DIS_NRORM = 21
SIM_DIR = 'simdir'